### ISSUE TITLE
How did you handle the JMS failure

### ISSUE THREAD

**Issue by apoorvpandey-ap** [javax4u/interview-questions#61]

**Comment by javax4u** [comment]
JMS implementation like ActiveMQ, Azure Service bus  has many configuration for failures. Most common is DLQ. Message can fall into this queue because of OverSize, Overstay or Overload of destination queue.

![image](https://user-images.githubusercontent.com/2442530/142183140-b65cee34-c946-4564-bcba-cbdac9648fd3.png)

**Comment by javax4u** [comment]
Q 1. What is the difference between primary key and Primary connection string in AZURE keys. And where and how will you will use it ?
